-- Seed: 'data_analysis' cross-cutting learning objective for subjects with graph/table/
-- numerical-dataset exam questions (Biology, Chemistry, Physics, Mathematics, Geography,
-- Economics, Psychology, Business). Distinct from 'source_analysis' (qualitative sources/
-- case studies) and 'practical_skills' (running an investigation) -- this is reading,
-- calculating from, and concluding from quantitative data already given in a question.

INSERT INTO learning_objectives (subject_id, code, objective, applies_to) VALUES
  ('1f8f77f9-308e-4da0-ac62-1f0ad994f409', 'data_analysis', 'Practise interpreting and calculating from graphs, tables, and data sets, then drawing valid conclusions.', ARRAY['notes', 'exam_practice']),
  ('8255c826-470e-4b74-9d57-a13468f81c4d', 'data_analysis', 'Practise interpreting and calculating from graphs, tables, and data sets, then drawing valid conclusions.', ARRAY['notes', 'exam_practice']),
  ('96ee8a9c-75e6-42e9-8adf-9ea77ddc1c4c', 'data_analysis', 'Practise interpreting and calculating from graphs, tables, and data sets, then drawing valid conclusions.', ARRAY['notes', 'exam_practice']),
  ('97e712aa-0fb7-44cc-b774-26b7a39c74f3', 'data_analysis', 'Practise interpreting and calculating from graphs, tables, and data sets, then drawing valid conclusions.', ARRAY['notes', 'exam_practice']),
  ('9c88ff48-a2b7-40ac-9b53-8321d24bf43d', 'data_analysis', 'Practise interpreting and calculating from graphs, tables, and data sets, then drawing valid conclusions.', ARRAY['notes', 'exam_practice']),
  ('f170610d-4fd2-4442-9b31-4f021deb09f9', 'data_analysis', 'Practise interpreting and calculating from graphs, tables, and data sets, then drawing valid conclusions.', ARRAY['notes', 'exam_practice']),
  ('0d346243-f41b-483b-ba01-94a0654c185c', 'data_analysis', 'Practise interpreting and calculating from graphs, tables, and data sets, then drawing valid conclusions.', ARRAY['notes', 'exam_practice']),
  ('6b6d5a60-fa2c-4aa4-8a6c-2e91f82eb2c5', 'data_analysis', 'Practise interpreting and calculating from graphs, tables, and data sets, then drawing valid conclusions.', ARRAY['notes', 'exam_practice']),
  ('907b45d6-b725-47a7-b50c-1b75bbf267d0', 'data_analysis', 'Practise interpreting and calculating from graphs, tables, and data sets, then drawing valid conclusions.', ARRAY['notes', 'exam_practice']),
  ('afd27c46-60bf-4227-9da6-b430726896e0', 'data_analysis', 'Practise interpreting and calculating from graphs, tables, and data sets, then drawing valid conclusions.', ARRAY['notes', 'exam_practice']),
  ('befcb76a-0833-4c89-a804-a4b8ad24b26d', 'data_analysis', 'Practise interpreting and calculating from graphs, tables, and data sets, then drawing valid conclusions.', ARRAY['notes', 'exam_practice']),
  ('d3586af0-e42b-495a-9f4a-1954aec4dfd1', 'data_analysis', 'Practise interpreting and calculating from graphs, tables, and data sets, then drawing valid conclusions.', ARRAY['notes', 'exam_practice']),
  ('0fb0712d-1705-4d61-af9e-bddd221fc031', 'data_analysis', 'Practise interpreting and calculating from graphs, tables, and data sets, then drawing valid conclusions.', ARRAY['notes', 'exam_practice']),
  ('4372e7ca-2171-4ac4-8e13-d3188c90163c', 'data_analysis', 'Practise interpreting and calculating from graphs, tables, and data sets, then drawing valid conclusions.', ARRAY['notes', 'exam_practice']),
  ('6ad4aded-18c3-42b9-9492-d97ef682b3b8', 'data_analysis', 'Practise interpreting and calculating from graphs, tables, and data sets, then drawing valid conclusions.', ARRAY['notes', 'exam_practice']),
  ('7ee71e48-f0de-478a-9a36-5616dcfb4d24', 'data_analysis', 'Practise interpreting and calculating from graphs, tables, and data sets, then drawing valid conclusions.', ARRAY['notes', 'exam_practice']),
  ('9004d350-50d2-47f2-be61-c9fa1c9984d0', 'data_analysis', 'Practise interpreting and calculating from graphs, tables, and data sets, then drawing valid conclusions.', ARRAY['notes', 'exam_practice']),
  ('e7e31e71-054c-4e45-83b5-eced108f8c97', 'data_analysis', 'Practise interpreting and calculating from graphs, tables, and data sets, then drawing valid conclusions.', ARRAY['notes', 'exam_practice']),
  ('03a6c403-47bd-4f0b-9d54-246b88b0a5e8', 'data_analysis', 'Practise interpreting and calculating from graphs, tables, and data sets, then drawing valid conclusions.', ARRAY['notes', 'exam_practice']),
  ('3cf1b1a3-6f64-4db2-b5ff-2443f608f3b1', 'data_analysis', 'Practise interpreting and calculating from graphs, tables, and data sets, then drawing valid conclusions.', ARRAY['notes', 'exam_practice']),
  ('c3825604-9c19-4b0f-84b9-4d5dc16f4f8c', 'data_analysis', 'Practise interpreting and calculating from graphs, tables, and data sets, then drawing valid conclusions.', ARRAY['notes', 'exam_practice']),
  ('d3fbc24d-2601-466f-810e-0ba202700f35', 'data_analysis', 'Practise interpreting and calculating from graphs, tables, and data sets, then drawing valid conclusions.', ARRAY['notes', 'exam_practice']),
  ('df69f485-7b8d-49bc-abc4-6da194ad0b79', 'data_analysis', 'Practise interpreting and calculating from graphs, tables, and data sets, then drawing valid conclusions.', ARRAY['notes', 'exam_practice']),
  ('464e64ec-2725-470d-a96d-a3a1524c3ccb', 'data_analysis', 'Practise interpreting and calculating from graphs, tables, and data sets, then drawing valid conclusions.', ARRAY['notes', 'exam_practice']),
  ('93e0919c-b8c2-43e7-a1c4-4fd30a62bc47', 'data_analysis', 'Practise interpreting and calculating from graphs, tables, and data sets, then drawing valid conclusions.', ARRAY['notes', 'exam_practice']),
  ('cacf8ad2-1bba-41f8-b3f7-26bab7cc678b', 'data_analysis', 'Practise interpreting and calculating from graphs, tables, and data sets, then drawing valid conclusions.', ARRAY['notes', 'exam_practice']),
  ('ddfa294a-8973-4267-90a5-570f3fb3e519', 'data_analysis', 'Practise interpreting and calculating from graphs, tables, and data sets, then drawing valid conclusions.', ARRAY['notes', 'exam_practice']),
  ('f75f76be-7c7c-45a8-b0ea-846c310c0f74', 'data_analysis', 'Practise interpreting and calculating from graphs, tables, and data sets, then drawing valid conclusions.', ARRAY['notes', 'exam_practice']),
  ('fe1dea26-8fec-4057-b7a2-63a2bf880534', 'data_analysis', 'Practise interpreting and calculating from graphs, tables, and data sets, then drawing valid conclusions.', ARRAY['notes', 'exam_practice']),
  ('2b3edc1e-92e4-4d72-97f7-10709c073177', 'data_analysis', 'Practise interpreting and calculating from graphs, tables, and data sets, then drawing valid conclusions.', ARRAY['notes', 'exam_practice']),
  ('37ca2048-92bb-4971-b431-112d81cb79ee', 'data_analysis', 'Practise interpreting and calculating from graphs, tables, and data sets, then drawing valid conclusions.', ARRAY['notes', 'exam_practice']),
  ('9671ad2e-fd49-4309-8621-a2e3c87e6126', 'data_analysis', 'Practise interpreting and calculating from graphs, tables, and data sets, then drawing valid conclusions.', ARRAY['notes', 'exam_practice']),
  ('9f5be3f9-5b8c-4e46-bbd5-1df2478c3825', 'data_analysis', 'Practise interpreting and calculating from graphs, tables, and data sets, then drawing valid conclusions.', ARRAY['notes', 'exam_practice']),
  ('a1b9f027-2c63-4865-9980-5d5c2a2387f0', 'data_analysis', 'Practise interpreting and calculating from graphs, tables, and data sets, then drawing valid conclusions.', ARRAY['notes', 'exam_practice']),
  ('f9427dc7-3774-40af-9a0a-e813b0984dce', 'data_analysis', 'Practise interpreting and calculating from graphs, tables, and data sets, then drawing valid conclusions.', ARRAY['notes', 'exam_practice']),
  ('12c93a4d-e524-495d-90a7-ebf2a55db6a5', 'data_analysis', 'Practise interpreting and calculating from graphs, tables, and data sets, then drawing valid conclusions.', ARRAY['notes', 'exam_practice']),
  ('303e474c-9bc5-4dd0-aa08-938d0072d9b4', 'data_analysis', 'Practise interpreting and calculating from graphs, tables, and data sets, then drawing valid conclusions.', ARRAY['notes', 'exam_practice']),
  ('574a5b26-b487-430f-9c2e-6f361cb3ce4c', 'data_analysis', 'Practise interpreting and calculating from graphs, tables, and data sets, then drawing valid conclusions.', ARRAY['notes', 'exam_practice']),
  ('80dacba3-d0e2-40b8-9e4e-adc5951f9010', 'data_analysis', 'Practise interpreting and calculating from graphs, tables, and data sets, then drawing valid conclusions.', ARRAY['notes', 'exam_practice']),
  ('98c8ff30-c814-40dd-a8ac-9888d47c5a8e', 'data_analysis', 'Practise interpreting and calculating from graphs, tables, and data sets, then drawing valid conclusions.', ARRAY['notes', 'exam_practice']),
  ('bb59a160-4304-46e6-a43b-fcdc114c65cd', 'data_analysis', 'Practise interpreting and calculating from graphs, tables, and data sets, then drawing valid conclusions.', ARRAY['notes', 'exam_practice']),
  ('0cb59b36-67e2-4647-9943-cf2ad8020263', 'data_analysis', 'Practise interpreting and calculating from graphs, tables, and data sets, then drawing valid conclusions.', ARRAY['notes', 'exam_practice']),
  ('617b0306-544a-4c18-bc40-5f75a96a527a', 'data_analysis', 'Practise interpreting and calculating from graphs, tables, and data sets, then drawing valid conclusions.', ARRAY['notes', 'exam_practice']),
  ('69ca59ea-fe51-4b47-8690-b2039a44b13b', 'data_analysis', 'Practise interpreting and calculating from graphs, tables, and data sets, then drawing valid conclusions.', ARRAY['notes', 'exam_practice']),
  ('842ad0d6-59ea-451a-834e-5792c3800185', 'data_analysis', 'Practise interpreting and calculating from graphs, tables, and data sets, then drawing valid conclusions.', ARRAY['notes', 'exam_practice']),
  ('9b215650-2e25-42c6-8242-ba7345347f99', 'data_analysis', 'Practise interpreting and calculating from graphs, tables, and data sets, then drawing valid conclusions.', ARRAY['notes', 'exam_practice']),
  ('ba8dbe41-aa5c-461e-8c64-0b78757acf29', 'data_analysis', 'Practise interpreting and calculating from graphs, tables, and data sets, then drawing valid conclusions.', ARRAY['notes', 'exam_practice'])
ON CONFLICT DO NOTHING;
